### PR TITLE
Fix NewPart property - it should be PartType instead of Name

### PR DESCRIPTION
**Pull request by jj09**

### CODE REVIEW

**Comment by bradolenick** [comment]
+Yvonne

**Comment by nickharris** [comment]
Hey JJ, 
- make the updates to dev branch rather then master_template branch
- make the updates in /templates/ folder rather then /generated/ folder. any changes to generated will be overwritten.

thanks for taking the time to update the docs!

nick

**Comment by jj09** [comment]
@nickharris: didn't hit CTRL+S hard enough on file in template folder 😨 

per @rowong I should do changes against master_template: https://github.com/Azure/portaldocs/pull/74

**Comment by rowong** [comment]
@jj09 You're both right.  Ideally you put it in both dev and master_template (dev so to avoid merge conflicts on merge and master_template so it gets updated sooner).  for the earlier changes, I just merged it to master_template

**Comment by jj09** [comment]
Can we add section submitting PR to https://github.com/Azure/portaldocs/blob/master/CONTRIBUTING.md ?
Currently it's not clear to which branch you should submit PR against. I also think adding very short section how to fix docs (without requirements) to regenerate them would be helpful and will encourage more people to contribute. I.e.: when I want to submit fix and I see 3 pages long document how to do it. I give up. If I see 3 lines long instructions then I'll probably do it.

**Comment by jj09** [comment]
ping

if somebody can review my answer: https://stackoverflow.microsoft.com/questions/100456/how-to-remove-part-and-do-not-break-users

perhaps we can port it to docs?

**Comment by rowong** [comment]
Started an email thread between you, yvonne, and adam to review your answer.

**Pull request closed without merging**
