### PR TITLE
Should be portalfx in stead of portalf in the breaking changes link

### PR DESCRIPTION
**Pull request by ppgovekar**
Should be portalfx in stead of portalf in the breaking changes link

### CODE REVIEW

**Comment by mikekinsman** [comment]
Docs Build status updates of commit _[e65372f](https://github.com/ppgovekar/portaldocs/pull/244/commits/e65372f8b87d1e816862a3001506fafcc0d09739)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[portal-sdk/generated/downloads.md](https://github.com/ppgovekar/portaldocs/blob/patch-1/portal-sdk/generated/downloads.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/azure/portal-sdk/portal-sdk/generated/downloads?branch=pr-en-us-244) | [Details](#user-content-85dbdc9c-319aa78c)

<a id="85dbdc9c-319aa78c"></a>
### [portal-sdk/generated/downloads.md](https://github.com/ppgovekar/portaldocs/blob/patch-1/portal-sdk/generated/downloads.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C22%5C3d86255f-f488-188e-02a3-9e92aa67830d%5CPullRequest%5C201907221629462984-244%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sOO9WtxLNbH%2Bmp%2BZMwqoxqKjdq%2ByJlwSed8puscVHCE%3D&st=2019-07-22T16%3A25%3A48Z&se=2019-08-22T16%3A30%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
Docs Build status updates of commit _[e65372f](https://github.com/ppgovekar/portaldocs/pull/244/commits/e65372f8b87d1e816862a3001506fafcc0d09739)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[portal-sdk/generated/downloads.md](https://github.com/ppgovekar/portaldocs/blob/patch-1/portal-sdk/generated/downloads.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/azure/portal-sdk/portal-sdk/generated/downloads?branch=pr-en-us-244) | [Details](#user-content-85dbdc9c-cc082040)

<a id="85dbdc9c-cc082040"></a>
### [portal-sdk/generated/downloads.md](https://github.com/ppgovekar/portaldocs/blob/patch-1/portal-sdk/generated/downloads.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C22%5C3d86255f-f488-188e-02a3-9e92aa67830d%5CPullRequest%5C201907221805475890-244%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EoILMJD%2BWx1AjyuCdjn0BgFfqpiqIZAAzwCR7M2XP2M%3D&st=2019-07-22T18%3A01%3A41Z&se=2019-08-22T18%3A06%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ppgovekar** [comment]
@nickharris please take a look

**Comment by ppgovekar** [comment]
My bad I only changed display link :S

**Pull request merged**
